# version: "3.9"

services:
  api-stripe-demo:
    image: api-stripe-demo
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - .:/home/node/app
    ports:
      - '3000:3000'
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      NODE_ENV: development
    command: tail -f /dev/null

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stripe_demo
    ports:
      - '3307:3306'
    command: --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  stripe_cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    tty: true
    stdin_open: true
    depends_on:
      - api-stripe-demo

volumes:
  mysql_data:
